// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9tmL8PJymCJ5NEKPL-ta0SHlm6wx7PmY',
    appId: '1:903942976987:web:3f88035fc5cbc3b0dfe3fe',
    messagingSenderId: '903942976987',
    projectId: 'plantdex-26ba9',
    authDomain: 'plantdex-26ba9.firebaseapp.com',
    storageBucket: 'plantdex-26ba9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHS8LC5Y5HLyiVAanAnFEN1V7ZHW3okIQ',
    appId: '1:903942976987:android:4b8856c34d0f8f10dfe3fe',
    messagingSenderId: '903942976987',
    projectId: 'plantdex-26ba9',
    storageBucket: 'plantdex-26ba9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarEiMuqNuj0kHLI1puZ-cfiU-MbXahNk',
    appId: '1:903942976987:ios:0e5ac93af7d474addfe3fe',
    messagingSenderId: '903942976987',
    projectId: 'plantdex-26ba9',
    storageBucket: 'plantdex-26ba9.appspot.com',
    iosBundleId: 'com.example.paMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarEiMuqNuj0kHLI1puZ-cfiU-MbXahNk',
    appId: '1:903942976987:ios:0b28a40718d3ff90dfe3fe',
    messagingSenderId: '903942976987',
    projectId: 'plantdex-26ba9',
    storageBucket: 'plantdex-26ba9.appspot.com',
    iosBundleId: 'com.example.paMobile.RunnerTests',
  );
}
